on:
  push:
    branches:
      - main
    paths: ["stories/**", "src/components/**"]
  workflow_dispatch: null

name: Publish stories if changed

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps and build Storybook
        run: npm install --legacy-peer-deps && npm run build:docs
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./storybook-static
          branch: gh-pages
          target-folder: docs/docs
          clean-exclude: pr-preview