on:
  push:
    branches:
      - main
    paths: ["stories/**", "src/components/**"]

name: Publish stories if changed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and deploy to storybook-static branch
        uses: JamesIves/github-pages-deploy-action@4.1.1
        env:
          branch: preview-env
          folder: docs/docs
          build_script: npm install && npm run build:docs
