on:
  push:
    branches:
      - main
    paths: ["stories/**", "src/components/**"]

name: Publish stories if changed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: npm install && npm run build:docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: preview-env
          folder: docs/docs
          target-folder: docs/docs/
      - name: Publish env
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Preview environment
          message: |
            ## Preview environment
            https://colpitts-dev.github.io/sb-pr-preview/docs/