on:
  push:
    branches:
      - main
    paths: ["stories/**", "src/components/**"]

name: Publish stories if changed

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master branch
        uses: actions/checkout@master
      - name: Merge master -> preview-env
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: preview-env
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: checkout preview-env branch
        uses: actions/checkout@v2
        with:
          ref: preview-env
      - run: |
          npm install
          npm build:docs
          mv docs/build docs/docs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build static storybook from master
          branch: preview-env
